apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: randomnumberapplication
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/georgesjamous/RandomNumberk8s.git
    targetRevision: HEAD
    path: defs
  destination:
    server: https://kubernetes.default.svc
    namespace: georges
  syncPolicy:
    automated:
      selfHeal: true
      prune: true